# Generated by Django 2.2.7 on 2019-12-19 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_auto_20191219_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Abreviação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_types_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_ypes_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'CompanyType',
                'verbose_name_plural': 'CompanyTypes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTaxRegime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Abreviação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_tax_regime_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_tax_regime_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'CompanyTaxRegime',
                'verbose_name_plural': 'CompanyTaxRegimes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='company.CompanyType', verbose_name='Tipo de Empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_regime',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='company.CompanyTaxRegime', verbose_name='Regime Tributário'),
        ),
    ]
