# Generated by Django 2.2.7 on 2019-12-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191219_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='company.CompanyType', verbose_name='Tipo de Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_regime',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='company.CompanyTaxRegime', verbose_name='Regime Tributário'),
        ),
    ]
