# Generated by Django 2.2.7 on 2019-12-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20191230_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
