# Generated by Django 2.2.7 on 2020-01-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20191230_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Abreviação'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
    ]
