# Generated by Django 2.2.9 on 2020-02-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200104_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_num',
            field=models.CharField(help_text='Apenas números', max_length=100, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Apenas números', max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_city',
            field=models.CharField(help_text='Ex: Campo Grande/MS, Porto Alegre/RS, Vitória/ES, Natal/RN', max_length=100, verbose_name='Cidade/Estado'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, default='', help_text='Apenas números', max_length=100, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=8, verbose_name='CEP'),
        ),
    ]
