# Generated by Django 2.2.7 on 2020-01-06 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0016_auto_20191217_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0009_auto_20200106_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityRequesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('abbreviation', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorityrequesting_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorityrequesting_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'AuthorityRequesting',
                'verbose_name_plural': 'AuthorityRequesting',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForensicScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forensicscan', models.TextField(verbose_name='Circunstância da Perícia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forensicscans_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forensicscans_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'ForensicScan',
                'verbose_name_plural': 'ForensicScan',
            },
        ),               
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Em Produção'), (1, 'Finalizado'), (2, 'Cancelado'), (3, 'Arquivado')], max_length=2, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportstatus_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportstatus_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'ReportStatus',
                'verbose_name_plural': 'ReportStatus',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_action', models.CharField(max_length=50, verbose_name='Natureza da Ação')),
                ('process_number', models.CharField(max_length=50, verbose_name='Número do Processo')),
                ('date_report', models.DateField(verbose_name='Data da Perícia')),
                ('anamnesis', models.TextField(verbose_name='Anamnese')),
                ('cid_number', models.CharField(max_length=50, verbose_name='Diagnóstico')),
                ('discussion', models.CharField(max_length=50, verbose_name='Discusão')),
                ('conclusion', models.TextField(verbose_name='Conclusão')),
                ('obs', models.TextField(verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('authority_requesting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.AuthorityRequesting', verbose_name='Autoridade Requisitante')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autor_patient_id', to='patient.Patients', verbose_name='Autor')),
                ('forensic_scan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.ForensicScan', verbose_name='Circunstância da Perícia')),
                ('proficient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proficient_patient_id', to='patient.Patients', verbose_name='Periciando')),
                ('profile_person_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.ProfilePersonType', verbose_name='Perito')),
                ('report_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.ReportStatus', verbose_name='Status')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Report',
                'ordering': ['id'],
            },
        ),        
        
        migrations.CreateModel(
            name='CidNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidnumbers_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidnumbers_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'CidNumber',
                'verbose_name_plural': 'CidNumbers',
                'ordering': ['name'],
            },
        ),
    ]
