# Generated by Django 2.2.7 on 2020-01-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstatus',
            name='obs',
            field=models.CharField(default='', max_length=100, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='authorityrequesting',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, verbose_name='OBS'),
        ),
        migrations.AlterField(
            model_name='reportstatus',
            name='status',
            field=models.CharField(max_length=2, verbose_name='Status'),
        ),
    ]
