# Generated by Django 2.2.7 on 2020-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200106_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstatus',
            name='obs',
            field=models.TextField(default='', verbose_name='Observação'),
        ),
    ]
