# Generated by Django 2.2.7 on 2020-01-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200106_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstatus',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Status'),
        ),
    ]
