# Generated by Django 2.2.7 on 2020-01-07 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0004_auto_20200106_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='discussion',
            field=models.CharField(max_length=50, verbose_name='Discussão'),
        ),
        migrations.AlterField(
            model_name='reportstatus',
            name='obs',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.CreateModel(
            name='NatureOfAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(max_length=100, verbose_name='Tipo da Ação')),
                ('obs', models.TextField(verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natureofaction_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natureofaction_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
        ),
    ]
