# Generated by Django 2.2.7 on 2020-01-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20200107_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='natureofaction',
            options={'ordering': ['type_action'], 'verbose_name': 'Nature Of Action', 'verbose_name_plural': 'Nature Of Actions'},
        ),
        migrations.AlterField(
            model_name='natureofaction',
            name='obs',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='report',
            name='nature_of_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.NatureOfAction', verbose_name='Natureza da Ação'),
        ),
    ]
