# Generated by Django 2.2.7 on 2020-01-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20200108_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='report.ReportStatus', verbose_name='Status'),
        ),
    ]
