# Generated by Django 2.2.7 on 2020-01-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20200108_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.ReportStatus', verbose_name='Status'),
        ),
    ]
