# Generated by Django 2.2.7 on 2020-01-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20200108_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='forensic_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='report.ForensicScan', verbose_name='Circunstância da Perícia'),
        ),
        migrations.AlterField(
            model_name='report',
            name='obs',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
    ]
