# Generated by Django 2.2.7 on 2020-01-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20200108_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forensicscan',
            options={'verbose_name': 'ForensicScan', 'verbose_name_plural': 'ForensicScans'},
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='nature_of_action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='report.NatureOfAction', verbose_name='Natureza da Ação'),
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='version',
            field=models.CharField(default='', max_length=100, verbose_name='Versão'),
        ),
    ]
