# Generated by Django 2.2.7 on 2020-01-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20200109_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forensicscan',
            name='nature_of_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.NatureOfAction', verbose_name='Natureza da Ação'),
        ),
    ]
