# Generated by Django 2.2.7 on 2020-01-11 03:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20200109_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicscan',
            name='anamnesis',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Anamnese'),
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='conclusion',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Conclusão'),
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='discussion',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Discussão'),
        ),
    ]
