# Generated by Django 2.2.7 on 2020-01-12 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20200111_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeitembynatureofaction',
            name='nature_of_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.NatureOfAction', verbose_name='Natureza da Ação'),
        ),
        migrations.AlterField(
            model_name='typeitembynatureofaction',
            name='question',
            field=models.TextField(blank=True, verbose_name='Pergunta?'),
        ),
    ]
