# Generated by Django 2.2.7 on 2020-01-12 04:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_auto_20200112_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeitembynatureofaction',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Pergunta?'),
        ),
    ]
