# Generated by Django 2.2.7 on 2020-01-13 04:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20200106_1009'),
        ('report', '0020_auto_20200112_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeitem',
            name='profile_person_type',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.PROTECT, to='person.ProfilePersonType', verbose_name='Perito'),
        ),
        migrations.AlterField(
            model_name='item',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Pergunta?'),
        ),
    ]
