# Generated by Django 2.2.7 on 2020-01-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20200106_1009'),
        ('report', '0021_auto_20200113_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeitembynatureofaction',
            name='profile_person_type',
            field=models.ForeignKey(default='16', on_delete=django.db.models.deletion.PROTECT, to='person.ProfilePersonType', verbose_name='Perito'),
        ),
        migrations.AlterField(
            model_name='typeitem',
            name='profile_person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.ProfilePersonType', verbose_name='Perito'),
        ),
    ]
