# Generated by Django 2.2.7 on 2020-01-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_auto_20200113_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeitembynatureofaction',
            name='profile_person_type',
        ),
    ]
