# Generated by Django 2.2.7 on 2020-01-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200104_1536'),
        ('report', '0024_remove_typeitem_profile_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeitem',
            name='department',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.PROTECT, to='company.Department', verbose_name='Departamento'),
        ),
    ]
