# Generated by Django 2.2.7 on 2020-01-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20200106_1009'),
        ('report', '0026_remove_typeitem_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeitem',
            name='person',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.PROTECT, to='person.Person', verbose_name='Departamento'),
        ),
    ]
