# Generated by Django 2.2.7 on 2020-01-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_typeitem_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeitem',
            name='person',
        ),
    ]
