# Generated by Django 2.2.7 on 2020-01-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20200106_1009'),
        ('report', '0028_remove_typeitem_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeitem',
            name='medical_specialty',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='person.MedicalSpecialty', verbose_name='Especialidade'),
        ),
    ]
