# Generated by Django 2.2.7 on 2020-01-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0029_typeitem_medical_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeitem',
            name='medical_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.MedicalSpecialty', verbose_name='Especialidade'),
        ),
    ]
