# Generated by Django 2.2.7 on 2020-01-14 20:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0030_auto_20200113_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeitem',
            name='medical_specialty',
        ),
        migrations.AlterField(
            model_name='item',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Perguntas?'),
        ),
    ]
