# Generated by Django 2.2.7 on 2020-01-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0031_auto_20200114_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='process_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número do Processo'),
        ),
    ]
