# Generated by Django 2.2.7 on 2020-01-14 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200104_1536'),
        ('report', '0032_auto_20200114_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeitembynatureofaction',
            name='department',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.PROTECT, to='company.Department', verbose_name='Departamento'),
        ),
    ]
