# Generated by Django 2.2.7 on 2020-01-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_typeitembynatureofaction_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeitembynatureofaction',
            name='department',
        ),
    ]
