# Generated by Django 2.2.8 on 2020-01-17 15:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0035_typeitembynatureofaction_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forensicscan',
            name='anamnesis',
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='anamnesis_family_background',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Familiares'),
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='anamnesis_general_exam',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Exame Físico Geral'),
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='anamnesis_history',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: História Pregressa da Doença Atual'),
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='anamnesis_medical_documents',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Documentos Médicos'),
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='anamnesis_mental_exam',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Exame do Estado Mental'),
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='anamnesis_personal_background',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Pessoais'),
        ),
        migrations.AlterField(
            model_name='item',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report', verbose_name='Laudo'),
        ),
    ]
