# Generated by Django 2.2.8 on 2020-01-17 15:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0036_auto_20200117_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='anamnesis',
        ),
        migrations.AddField(
            model_name='report',
            name='anamnesis_family_background',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Familiares'),
        ),
        migrations.AddField(
            model_name='report',
            name='anamnesis_general_exam',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Exame Físico Geral'),
        ),
        migrations.AddField(
            model_name='report',
            name='anamnesis_history',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: História Pregressa da Doença Atual'),
        ),
        migrations.AddField(
            model_name='report',
            name='anamnesis_medical_documents',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Documentos Médicos'),
        ),
        migrations.AddField(
            model_name='report',
            name='anamnesis_mental_exam',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Exame do Estado Mental'),
        ),
        migrations.AddField(
            model_name='report',
            name='anamnesis_personal_background',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Pessoais'),
        ),
    ]
