# Generated by Django 2.2.8 on 2020-01-17 15:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0037_auto_20200117_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicscan',
            name='anamnesis_diagnosis',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Diagnóstico'),
        ),
        migrations.AddField(
            model_name='report',
            name='anamnesis_diagnosis',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Diagnóstico'),
        ),
    ]
