# Generated by Django 2.2.8 on 2020-01-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0038_auto_20200117_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cid_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Diagnóstico'),
        ),
    ]
