# Generated by Django 2.2.8 on 2020-01-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0039_auto_20200118_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicscan',
            name='cid_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Informe o CID'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_diagnosis',
            field=models.TextField(blank=True, verbose_name='Anamnese: Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_diagnosis',
            field=models.TextField(blank=True, verbose_name='Anamnese: Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cid_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Informe o CID'),
        ),
    ]
