# Generated by Django 2.2.8 on 2020-01-19 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0040_auto_20200118_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='anamnesis_medical_documents',
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(blank=True, verbose_name='Documentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report', verbose_name='Laudo')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaldocument_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaldocument_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
        ),
    ]
