# Generated by Django 2.2.8 on 2020-01-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0041_auto_20200119_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forensicscan',
            name='anamnesis_medical_documents',
        ),
    ]
