# Generated by Django 2.2.8 on 2020-01-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0042_remove_forensicscan_anamnesis_medical_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_family_background',
            field=models.TextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Familiares'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_general_exam',
            field=models.TextField(blank=True, verbose_name='Anamnese: Exame Físico Geral'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_history',
            field=models.TextField(blank=True, verbose_name='Anamnese: História Pregressa da Doença Atual'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_mental_exam',
            field=models.TextField(blank=True, verbose_name='Anamnese: Exame do Estado Mental'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_personal_background',
            field=models.TextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Pessoais'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='Conclusão'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='discussion',
            field=models.TextField(blank=True, verbose_name='Discussão'),
        ),
    ]
