# Generated by Django 2.2.9 on 2020-01-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0044_item2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item2',
            name='type_item_by_nature_of_action',
        ),
        migrations.AddField(
            model_name='item2',
            name='type_item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='report.TypeItem', verbose_name='Tipo do Quesito'),
        ),
    ]
