# Generated by Django 2.2.9 on 2020-01-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0045_auto_20200121_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item2',
            name='type_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.TypeItem', verbose_name='Tipo do Quesito'),
        ),
    ]
