# Generated by Django 2.2.9 on 2020-01-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0046_auto_20200121_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='anamnesis_family_background',
            field=models.TextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Familiares'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_general_exam',
            field=models.TextField(blank=True, verbose_name='Anamnese: Exame Físico Geral'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_history',
            field=models.TextField(blank=True, verbose_name='Anamnese: História Pregressa da Doença Atual'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_mental_exam',
            field=models.TextField(blank=True, verbose_name='Anamnese: Exame do Estado Mental'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_personal_background',
            field=models.TextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Pessoais'),
        ),
        migrations.AlterField(
            model_name='report',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='Conclusão'),
        ),
        migrations.AlterField(
            model_name='report',
            name='discussion',
            field=models.TextField(blank=True, verbose_name='Discussão'),
        ),
        migrations.AlterField(
            model_name='typeitembynatureofaction',
            name='question',
            field=models.TextField(blank=True, verbose_name='Pergunta?'),
        ),
    ]
