# Generated by Django 2.2.9 on 2020-01-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0048_delete_itemsanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
