# Generated by Django 2.2.9 on 2020-01-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0051_auto_20200125_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidnumber',
            name='category',
            field=models.CharField(max_length=7, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='cidnumber',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cid_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='report.CidNumber', verbose_name='CID'),
        ),
    ]
