# Generated by Django 2.2.9 on 2020-01-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0052_auto_20200125_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='cid_number',
        ),
        migrations.AddField(
            model_name='cidnumber',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.Report', verbose_name='Laudo'),
        ),
        migrations.AddField(
            model_name='cidnumber',
            name='type_cid',
            field=models.BooleanField(default=True, verbose_name='Informe o CID primário'),
        ),
    ]
