# Generated by Django 2.2.9 on 2020-01-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0055_auto_20200125_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidnumber',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report', verbose_name='Laudo'),
        ),
        migrations.AlterField(
            model_name='cidnumber',
            name='type_cid',
            field=models.BooleanField(default=False, verbose_name='Informe o CID primário'),
        ),
    ]
