# Generated by Django 2.2.9 on 2020-01-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0056_auto_20200125_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidnumber',
            options={'ordering': ['-type_cid', 'category'], 'verbose_name': 'CidNumber', 'verbose_name_plural': 'CidNumbers'},
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='cid_number',
            field=models.TextField(blank=True, max_length=100, verbose_name='Informe o CID'),
        ),
    ]
