# Generated by Django 2.2.9 on 2020-01-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0058_locationobjective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forensicscan',
            name='forensicscan',
        ),
        migrations.RemoveField(
            model_name='forensicscan',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='forensicscan',
            name='profile_person_type',
        ),
        migrations.RemoveField(
            model_name='locationobjective',
            name='forensicscan',
        ),
        migrations.AddField(
            model_name='forensicscan',
            name='location_objective',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='report.LocationObjective', verbose_name='Circunstacia da Perícia'),
        ),
        migrations.AddField(
            model_name='locationobjective',
            name='forensic_scan',
            field=models.TextField(default='', verbose_name='Circunstância da Perícia'),
        ),
    ]
