# Generated by Django 2.2.9 on 2020-01-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0059_auto_20200125_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationobjective',
            name='version',
            field=models.CharField(default='', max_length=100, verbose_name='Versão'),
        ),
    ]
