# Generated by Django 2.2.9 on 2020-01-27 17:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0060_locationobjective_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationobjective',
            options={'verbose_name': 'LocationObjective', 'verbose_name_plural': 'LocationObjectives'},
        ),
        migrations.AddField(
            model_name='typeitembynatureofaction',
            name='cid_number',
            field=models.CharField(default='', max_length=100, verbose_name='CID-10'),
        ),
        migrations.AlterField(
            model_name='authorityrequesting',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Forma de tratamento da Autoridade'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_family_background',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Familiares'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_general_exam',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Exame Físico Geral'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_history',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: História Pregressa da Doença Atual'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_mental_exam',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Exame do Estado Mental'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='anamnesis_personal_background',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Pessoais'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='cid_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Informe o CID'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='conclusion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Conclusão'),
        ),
        migrations.AlterField(
            model_name='forensicscan',
            name='discussion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Discussão'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Pergunta?'),
        ),
        migrations.AlterField(
            model_name='locationobjective',
            name='forensic_scan',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Circunstância da Perícia'),
        ),
        migrations.AlterField(
            model_name='locationobjective',
            name='goal',
            field=ckeditor.fields.RichTextField(verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_family_background',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Familiares'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_general_exam',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Exame Físico Geral'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_history',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: História Pregressa da Doença Atual'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_mental_exam',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Exame do Estado Mental'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis_personal_background',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Antecedentes Patológicos Pessoais'),
        ),
        migrations.AlterField(
            model_name='report',
            name='conclusion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Conclusão'),
        ),
        migrations.AlterField(
            model_name='report',
            name='discussion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Discussão'),
        ),
        migrations.AlterField(
            model_name='typeitembynatureofaction',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Pergunta?'),
        ),
    ]
