# Generated by Django 2.2.9 on 2020-01-27 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0062_auto_20200127_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeitembynatureofaction',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Resposta'),
        ),
    ]
