# Generated by Django 2.2.9 on 2020-01-27 21:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0063_typeitembynatureofaction_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forensicscan',
            name='version',
            field=models.CharField(max_length=100, verbose_name='Versão'),
        ),
        migrations.CreateModel(
            name='DiscussionConclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid_number', models.CharField(max_length=100, verbose_name='Informe o CID')),
                ('discussion', ckeditor.fields.RichTextField(blank=True, verbose_name='Discussão')),
                ('conclusion', ckeditor.fields.RichTextField(blank=True, verbose_name='Conclusão')),
                ('inability_professional', models.CharField(choices=[('uniprofissional', 'uniprofissional'), ('multiprofissional', 'multiprofissional'), ('omniprofissional', 'omniprofissional')], max_length=100, verbose_name='Incapacidade da Atividade Desenvolvida')),
                ('inability_temporal', models.CharField(choices=[('temporária', 'temporária'), ('permanente', 'permanente')], max_length=100, verbose_name='Duração da Incapacidade')),
                ('version', models.CharField(max_length=100, verbose_name='Versão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussionconclusion_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussionconclusion_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'DiscussionConclusion',
                'verbose_name_plural': 'DiscussionConclusions',
            },
        ),
    ]
