# Generated by Django 2.2.9 on 2020-01-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0064_auto_20200127_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionconclusion',
            name='cid_number',
            field=models.CharField(max_length=7, verbose_name='Informe o CID'),
        ),
    ]
