# Generated by Django 2.2.9 on 2020-01-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0066_auto_20200128_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forensicscan',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='forensicscan',
            name='discussion',
        ),
    ]
