# Generated by Django 2.2.9 on 2020-01-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0068_auto_20200128_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='anamnesis_diagnosis',
        ),
    ]
