# Generated by Django 2.2.9 on 2020-01-29 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0069_remove_report_anamnesis_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location_objective',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='report.LocationObjective', verbose_name='Local e Objetivo'),
        ),
    ]
