# Generated by Django 2.2.9 on 2020-01-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0071_auto_20200128_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forensicscan',
            name='location_objective',
        ),
        migrations.AlterField(
            model_name='report',
            name='forensic_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='report.ForensicScan', verbose_name='Qual modelo de anamnese?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='report.LocationObjective', verbose_name='Local e Objetivo'),
        ),
    ]
