# Generated by Django 2.2.9 on 2020-01-30 15:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0074_auto_20200129_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='impress',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Impressão'),
        ),
    ]
