# Generated by Django 2.2.9 on 2020-01-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0075_report_impress'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='inability_professional',
            field=models.CharField(blank=True, choices=[('', 'ESCOLHA'), ('uniprofissional', 'uniprofissional'), ('multiprofissional', 'multiprofissional'), ('omniprofissional', 'omniprofissional')], max_length=100, null=True, verbose_name='Incapacidade Profissional'),
        ),
        migrations.AddField(
            model_name='report',
            name='inability_temporal',
            field=models.CharField(blank=True, choices=[('', 'ESCOLHA'), ('temporária', 'temporária'), ('permanente', 'permanente')], max_length=100, null=True, verbose_name='Duração da Incapacidade'),
        ),
        migrations.AlterField(
            model_name='discussionconclusion',
            name='inability_professional',
            field=models.CharField(choices=[('', 'ESCOLHA'), ('uniprofissional', 'uniprofissional'), ('multiprofissional', 'multiprofissional'), ('omniprofissional', 'omniprofissional')], max_length=100, verbose_name='Incapacidade Profissional'),
        ),
        migrations.AlterField(
            model_name='discussionconclusion',
            name='inability_temporal',
            field=models.CharField(choices=[('', 'ESCOLHA'), ('temporária', 'temporária'), ('permanente', 'permanente')], max_length=100, verbose_name='Duração da Incapacidade'),
        ),
    ]
