# Generated by Django 2.2.9 on 2020-02-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0077_auto_20200130_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionconclusion',
            name='profile_person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.ProfilePersonType', verbose_name='Perito'),
        ),
    ]
