# Generated by Django 2.2.9 on 2020-02-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_person_avatar'),
        ('report', '0078_auto_20200205_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeitembynatureofaction',
            name='doctor',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='person.Doctor', verbose_name='Perito'),
        ),
    ]
