# Generated by Django 2.2.9 on 2020-02-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0080_auto_20200205_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeitembynatureofaction',
            name='company',
        ),
    ]
