# Generated by Django 2.2.9 on 2020-02-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_person_avatar'),
        ('report', '0081_remove_typeitembynatureofaction_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='profile_person_type',
        ),
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='person.Doctor', verbose_name='Perito'),
        ),
    ]
