# Generated by Django 2.2.9 on 2020-02-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0086_auto_20200205_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorityrequesting',
            name='doctor',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.PROTECT, to='person.Doctor', verbose_name='Perito'),
        ),
    ]
