# Generated by Django 2.2.9 on 2020-02-07 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0087_auto_20200205_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorityrequesting',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Doctor', verbose_name='Perito'),
        ),
        migrations.AlterField(
            model_name='discussionconclusion',
            name='version',
            field=models.CharField(max_length=500, verbose_name='Versão'),
        ),
    ]
