# Generated by Django 2.2.9 on 2020-02-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0088_auto_20200207_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionconclusion',
            name='version',
            field=models.TextField(verbose_name='Versão'),
        ),
    ]
