# Generated by Django 2.2.9 on 2020-02-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0090_auto_20200207_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeitembynatureofaction',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Doctor', verbose_name='Perito'),
        ),
    ]
