# Generated by Django 2.2.9 on 2020-02-21 15:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0092_auto_20200221_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='anamnesis_conditions',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: Condições de Parto e Desenvolvimento Neuropsicomotor'),
        ),
        migrations.AddField(
            model_name='report',
            name='anamnesis_family',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: História Familiar'),
        ),
        migrations.AddField(
            model_name='report',
            name='anamnesis_professional',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anamnese: História Profissional'),
        ),
    ]
