# Generated by Django 2.2.7 on 2019-11-26 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('abbreviation', models.CharField(blank=True, max_length=100, verbose_name='Abrev')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Religions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('abbreviation', models.CharField(blank=True, max_length=100, verbose_name='Abrev')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('dt_birthday', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=30, verbose_name='RG')),
                ('rg_exped', models.CharField(max_length=100, verbose_name='Expedição')),
                ('rg_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('name_mother', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('name_father', models.CharField(blank=True, max_length=100, verbose_name='Nome do Pai')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('uf_natural', models.CharField(max_length=100, verbose_name='Natural')),
                ('origin', models.CharField(max_length=100, verbose_name='Procedência')),
                ('schooling', models.CharField(choices=[('0', 'Analfabeto'), ('1', 'Ensino Fundamental Incompleto'), ('2', 'Ensino Fundamental Completo'), ('3', 'Ensino Médio Completo'), ('4', 'Ensino Médio Incompleto'), ('5', 'Ensino Superior Completo'), ('6', 'Ensino Superior Incompleto')], max_length=100, verbose_name='Escolaridade')),
                ('situation_inss', models.CharField(max_length=100, verbose_name='Situação INSS')),
                ('scort', models.CharField(choices=[('0', 'Esposo(a)'), ('1', 'Filho(a)'), ('2', 'Pai'), ('3', 'Mãe'), ('4', 'Tio(a)'), ('6', 'Primo(a)'), ('7', 'Advogado(a)'), ('8', 'Avô(ó)'), ('9', 'Amigo(a)')], max_length=100, verbose_name='Acompanhante')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('maritalstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.MaritalStatus', verbose_name='Estado Civil')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Religions', verbose_name='Religião')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
