# Generated by Django 2.2.7 on 2019-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='cpf',
            field=models.CharField(help_text='Apenas números', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='name',
            field=models.CharField(help_text='Ajuda', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='rg',
            field=models.CharField(help_text='Apenas números', max_length=30, verbose_name='Nº RG'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='rg_exped',
            field=models.CharField(max_length=100, verbose_name='Orgão Expedidor'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='rg_uf',
            field=models.CharField(max_length=2, verbose_name='RG - UF'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='uf_natural',
            field=models.CharField(max_length=100, verbose_name='Naturalidade'),
        ),
    ]
