# Generated by Django 2.2.7 on 2019-12-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20191205_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
    ]
