# Generated by Django 2.2.7 on 2019-12-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patients_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maritalstatus',
            options={'verbose_name': 'MaritalStatus', 'verbose_name_plural': 'MaritalStatus'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='religions',
            options={'verbose_name': 'Religion', 'verbose_name_plural': 'Religions'},
        ),
        migrations.AlterField(
            model_name='patients',
            name='rg_exped',
            field=models.CharField(help_text='Ex: SSP / DETRAN / FORÇAS ARMADAS / CREA / OAB', max_length=100, verbose_name='Orgão Expedidor'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='situation_inss',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=100, verbose_name='Situação INSS'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='uf_natural',
            field=models.CharField(help_text='Ex: Campo Grande/MS, Porto Alegre/RS, Vitória/ES, Natal/RN', max_length=100, verbose_name='Naturalidade'),
        ),
    ]
