# Generated by Django 2.2.7 on 2019-12-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20191209_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='situation_inss',
            field=models.CharField(choices=[('', 'ESCOLHA'), ('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], default='', max_length=100, verbose_name='Situação INSS'),
        ),
    ]
