# Generated by Django 2.2.7 on 2019-12-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20191210_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.CharField(blank=True, help_text='(XX)XXXX-XXXX', max_length=30, verbose_name='Telefone'),
        ),
    ]
