# Generated by Django 2.2.7 on 2019-12-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20191211_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
