# Generated by Django 2.2.7 on 2019-12-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20191211_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='CEP',
            field=models.CharField(blank=True, max_length=100, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='patients',
            name='address_city_uf',
            field=models.CharField(blank=True, help_text='Ex: Campo Grande/MS, Porto Alegre/RS, Vitória/ES, Natal/RN', max_length=100, verbose_name='Cidade/UF'),
        ),
        migrations.AddField(
            model_name='patients',
            name='address_num',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nº'),
        ),
        migrations.AddField(
            model_name='patients',
            name='blood_rh',
            field=models.CharField(blank=True, max_length=2, verbose_name='FATOR RH'),
        ),
        migrations.AddField(
            model_name='patients',
            name='blood_type',
            field=models.CharField(blank=True, max_length=1, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.CharField(blank=True, help_text='Ex:(XX)XXXX-XXXX', max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='rg_uf',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='RG - UF'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='scort_type',
            field=models.CharField(blank=True, choices=[('', 'ESCOLHA'), ('0', 'Esposo(a)'), ('1', 'Filho(a)'), ('2', 'Pai'), ('3', 'Mãe'), ('4', 'Tio(a)'), ('6', 'Primo(a)'), ('7', 'Advogado(a)'), ('8', 'Avô(ó)'), ('9', 'Amigo(a)'), ('10', 'Não Informado')], max_length=100, verbose_name='Parentesco do Acompanhante'),
        ),
    ]
