# Generated by Django 2.2.7 on 2019-12-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20191214_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='CEP',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=7, verbose_name='CEP'),
        ),
    ]
