# Generated by Django 2.2.7 on 2019-12-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20191214_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='CEP',
            new_name='cep',
        ),
    ]
