# Generated by Django 2.2.8 on 2020-01-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_auto_20191217_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='schooling',
            field=models.CharField(choices=[('', 'ESCOLHA'), ('Analfabeto', 'Analfabeto'), ('Ensino Fundamental Incompleto', 'Ensino Fundamental Incompleto'), ('Ensino Fundamental Completo', 'Ensino Fundamental Completo'), ('Ensino Médio Completo', 'Ensino Médio Completo'), ('Ensino Médio Incompleto', 'Ensino Médio Incompleto'), ('Ensino Superior Completo', 'Ensino Superior Completo'), ('Ensino Superior Incompleto', 'Ensino Superior Incompleto')], max_length=100, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='scort_type',
            field=models.CharField(blank=True, choices=[('', 'ESCOLHA'), ('Esposo(a)', 'Esposo(a)'), ('Filho(a)', 'Filho(a)'), ('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Tio(a)', 'Tio(a)'), ('Primo(a)', 'Primo(a)'), ('Advogado(a)', 'Advogado(a)'), ('Avô(ó)', 'Avô(ó)'), ('9', 'Amigo(a)'), ('Não Informado', 'Não Informado')], max_length=100, verbose_name='Parentesco do Acompanhante'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.CharField(choices=[('', 'ESCOLHA'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
