# Generated by Django 2.2.8 on 2020-01-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_auto_20200120_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.CharField(choices=[('', 'ESCOLHA'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=100, verbose_name='Sexo'),
        ),
    ]
