# Generated by Django 2.2.9 on 2020-02-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_patients_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='maritalstatus',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='patient.MaritalStatus', verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='religion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='patient.Religions', verbose_name='Religião'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='schooling',
            field=models.CharField(blank=True, choices=[('', 'ESCOLHA'), ('Analfabeto', 'Analfabeto'), ('Ensino Fundamental Incompleto', 'Ensino Fundamental Incompleto'), ('Ensino Fundamental Completo', 'Ensino Fundamental Completo'), ('Ensino Médio Completo', 'Ensino Médio Completo'), ('Ensino Médio Incompleto', 'Ensino Médio Incompleto'), ('Ensino Superior Completo', 'Ensino Superior Completo'), ('Ensino Superior Incompleto', 'Ensino Superior Incompleto')], max_length=100, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='situation_inss',
            field=models.CharField(blank=True, choices=[('', 'ESCOLHA'), ('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=100, verbose_name='Situação INSS'),
        ),
    ]
