# Generated by Django 2.2.9 on 2020-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_auto_20200214_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='scort_type',
            field=models.CharField(blank=True, choices=[('', 'ESCOLHA'), ('Esposo(a)', 'Esposo(a)'), ('Filho(a)', 'Filho(a)'), ('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Tio(a)', 'Tio(a)'), ('Primo(a)', 'Primo(a)'), ('Advogado(a)', 'Advogado(a)'), ('Avô(ó)', 'Avô(ó)'), ('Amigo(a)', 'Amigo(a)'), ('Não Informado', 'Não Informado'), ('Sem acompanhante', 'Sem acompanhante')], max_length=100, verbose_name='Parentesco do Acompanhante'),
        ),
    ]
