# Generated by Django 2.2.9 on 2020-02-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_auto_20200214_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='maritalstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patient.MaritalStatus', verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patient.Religions', verbose_name='Religião'),
        ),
    ]
