# Generated by Django 2.2.7 on 2019-12-17 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0016_auto_20191217_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='CNPJ')),
                ('state_registration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inscrição Estadual')),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Abreviação')),
                ('tax_regime', models.CharField(blank=True, max_length=100, null=True, verbose_name='Regime Tributário')),
                ('company_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Empresa')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('number', models.CharField(max_length=100, verbose_name='Número')),
                ('burgh', models.CharField(max_length=100, verbose_name='Bairro')),
                ('state_city', models.CharField(max_length=100, verbose_name='Cidade/Estado')),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sigla')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Company', verbose_name='Empresa')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('date_birthday', models.DateTimeField(max_length=100, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('uf_natural', models.CharField(max_length=2, verbose_name='Natural')),
                ('rg', models.CharField(blank=True, help_text='Apenas números', max_length=30, verbose_name='Nº RG')),
                ('rg_exped', models.CharField(blank=True, help_text='Ex: SSP / DETRAN / FORÇAS ARMADAS / CREA / OAB', max_length=100, verbose_name='Orgão Expedidor')),
                ('rg_uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='RG - UF')),
                ('pis_pasep', models.CharField(blank=True, max_length=100, verbose_name='PIS/PASEP')),
                ('voter_title_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Titulo de Eleitor')),
                ('voter_title_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seção')),
                ('voter_title_zone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona Eleitoral')),
                ('voter_title_uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF - Titulo Eleitor')),
                ('cnh_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número CNH')),
                ('cnh_uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True, verbose_name='CNH - UF')),
                ('cnh_validate', models.DateField(blank=True, max_length=100, null=True, verbose_name='Validade')),
                ('cnh_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('address_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº')),
                ('address_city_uf', models.CharField(blank=True, help_text='Ex: Campo Grande/MS, Porto Alegre/RS, Vitória/ES, Natal/RN', max_length=100, null=True, verbose_name='Cidade/UF')),
                ('cep', models.CharField(blank=True, help_text='Apenas Números', max_length=8, null=True, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('so', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operacional')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Navegador')),
                ('maritalstatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.MaritalStatus', verbose_name='Estado Civil')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persontype_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persontype_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'PersonType',
                'verbose_name_plural': 'PersonTypes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Department', verbose_name='Departamento')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Person', verbose_name='Pessoa')),
                ('person_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.PersonType', verbose_name='Tipo de Pessoa')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profilepersontype_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profilepersontype_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'ProfilePersonType',
                'verbose_name_plural': 'ProfilePersonTypes',
                'ordering': ['person'],
            },
        ),
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicalspecialty_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicalspecialty_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'MedicalSpecialty',
                'verbose_name_plural': 'MedicalSpecialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_num', models.CharField(max_length=30, verbose_name='CRM')),
                ('crm_uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='RG - UF')),
                ('course', models.TextField(blank=True, null=True, verbose_name='Titulos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('medical_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.MedicalSpecialty', verbose_name='Especialidade Médica')),
                ('profile_person_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.ProfilePersonType', verbose_name='Pessoa')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['profile_person_type'],
            },
        ),
    ]
