# Generated by Django 2.2.7 on 2019-12-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20191217_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cnh_num',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, null=True, verbose_name='Número CNH'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(help_text='Apenas números', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_birthday',
            field=models.DateField(max_length=100, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='voter_title_num',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, null=True, verbose_name='Número do Titulo de Eleitor'),
        ),
    ]
