# Generated by Django 2.2.7 on 2019-12-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20191217_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='date_birthday',
            new_name='dt_birthday',
        ),
    ]
