# Generated by Django 2.2.7 on 2019-12-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20191217_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='medicalspecialty',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='persontype',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='profilepersontype',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
