# Generated by Django 2.2.7 on 2019-12-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20191218_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.RemoveField(
            model_name='department',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='department',
            name='user_updated',
        ),
        migrations.AlterField(
            model_name='person',
            name='pis_pasep',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, verbose_name='PIS/PASEP'),
        ),
        migrations.AlterField(
            model_name='person',
            name='voter_title_section',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, null=True, verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='person',
            name='voter_title_zone',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, null=True, verbose_name='Zona Eleitoral'),
        ),
        migrations.AlterField(
            model_name='profilepersontype',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Department', verbose_name='Departamento'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
