# Generated by Django 2.2.7 on 2020-01-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20191218_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='crm_num',
            field=models.CharField(help_text='Apenas Números', max_length=30, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='crm_uf',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='CRM - UF'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='medical_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.MedicalSpecialty', verbose_name='Especialidade Médica'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.ProfilePersonType', verbose_name='Perito'),
        ),
    ]
