# Generated by Django 2.2.7 on 2020-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20200104_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='course',
            field=models.TextField(default='', verbose_name='Titulos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_city_uf',
            field=models.CharField(blank=True, help_text='Ex: Campo Grande/MS, Porto Alegre/RS, Vitória/ES, Natal/RN', max_length=100, verbose_name='Cidade/UF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_num',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nº'),
        ),
        migrations.AlterField(
            model_name='person',
            name='browser',
            field=models.CharField(blank=True, max_length=100, verbose_name='Navegador'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cep',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cnh_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cnh_num',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, verbose_name='Número CNH'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cnh_uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='CNH - UF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ip',
            field=models.CharField(blank=True, max_length=100, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='person',
            name='so',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional'),
        ),
        migrations.AlterField(
            model_name='person',
            name='voter_title_num',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, verbose_name='Número do Titulo de Eleitor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='voter_title_section',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='person',
            name='voter_title_uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='UF - Titulo Eleitor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='voter_title_zone',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, verbose_name='Zona Eleitoral'),
        ),
    ]
