# Generated by Django 2.2.8 on 2020-01-18 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0010_doctorslist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorsList',
            new_name='DoctorList',
        ),
    ]
