# Generated by Django 2.2.8 on 2020-01-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0012_doctorlist_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cid10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cid10_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cid10_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Cid10',
                'verbose_name_plural': 'Cid10',
                'ordering': ['category'],
            },
        ),
    ]
