# Generated by Django 2.2.8 on 2020-01-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_cid10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cid10',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='cid10',
            name='user_updated',
        ),
        migrations.AddField(
            model_name='cid10',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='cid10',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
