# Generated by Django 2.2.8 on 2020-01-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_auto_20200118_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cid10',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
