# Generated by Django 2.2.8 on 2020-01-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_auto_20200118_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=50, verbose_name='Sexo'),
        ),
    ]
