# Generated by Django 2.2.9 on 2020-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_auto_20200120_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='crm_uf',
            field=models.CharField(max_length=2, verbose_name='CRM - UF'),
        ),
        migrations.AlterField(
            model_name='doctorlist',
            name='state',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cnh_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='CNH - UF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rg_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='RG - UF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='voter_title_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF - Titulo Eleitor'),
        ),
    ]
