# Generated by Django 2.2.9 on 2020-02-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_auto_20200123_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_num',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=100, verbose_name='Nº'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cnh_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=100, verbose_name='CNH - Categoria'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cnh_validate',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='CNH - Validade'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uf_natural',
            field=models.CharField(help_text='Ex: Campo Grande/MS, Porto Alegre/RS, Vitória/ES, Natal/RN', max_length=100, verbose_name='Natural'),
        ),
    ]
