# Generated by Django 2.2.9 on 2020-02-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_auto_20200131_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photo/peoples/', verbose_name='Foto'),
        ),
    ]
